name: CI/CD pipeline

on:
  push:
    branches:
      - main

env:
  IMAGE_BACKEND: ${{ secrets.DOCKER_USERNAME }}/fastapi-app:latest
  IMAGE_FRONTEND: ${{ secrets.DOCKER_USERNAME }}/react-app:latest

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Debug Files
        run: ls -R

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Backend
      - name: Build Backend Image
        run: docker build -t $IMAGE_BACKEND ./backend

      - name: Verify Backend Image
        run: docker images

      - name: Push Backend Image
        run: docker push $IMAGE_BACKEND

      # Frontend
      - name: Build Frontend Image
        run: docker build -t $IMAGE_FRONTEND ./frontend

      - name: Push Frontend Image
        run: docker push $IMAGE_FRONTEND
